import type { EdiV2LaboratoryProfile, EdiV2VisualMode } from "./types";

export const EDI_V2_LABORATORY_PRESETS: Record<EdiV2VisualMode, EdiV2LaboratoryProfile> = {
  prototype: { mode: "prototype", shaderMode: "composite", bloomIntensity: 1, bloomRadius: .72, bloomThreshold: .18, heartIntensity: 1, heartPulseSpeed: 1, heartRadius: .48, heartNoise: .7, heartGlow: 1, plasmaIntensity: 1, plasmaFlowSpeed: .65, plasmaNoiseScale: 1, plasmaEnergyMix: .5, plasmaSoftness: 1, filamentDensity: .8, filamentSpeed: .22, filamentThickness: .018, filamentGlow: .72, filamentPulseStrength: .65, magneticIntensity: .65, fieldStrength: 1, fieldSpeed: .35, fieldDistortion: .8, fieldThickness: .035, fieldOpacity: .55, particleDensity: 1, particleSpeed: .28, particleSize: 4, particleOpacity: .65, particleLife: 1, knowledgeFlow: .72, thoughtPulseStrength: .72, thoughtPulseRadius: .82, thoughtPulseSpeed: .32, thoughtPulseWidth: .055, thoughtPulseGlow: .8, thoughtPulseDecay: .72, communicationStrength: .68, communicationRadius: 1.08, communicationSpeed: .28, communicationWidth: .045, communicationGlow: .72, communicationDecay: .76, presence: .72, presenceRadius: .88, presenceSoftness: .72, presenceOpacity: .24, presencePulse: .42, distortionIntensity: 1, pulseIntensity: 1, animationSpeed: 1, paused: false },
  minimal: { mode: "minimal", shaderMode: "composite", bloomIntensity: .45, bloomRadius: .42, bloomThreshold: .34, heartIntensity: .82, heartPulseSpeed: .72, heartRadius: .44, heartNoise: .35, heartGlow: .55, plasmaIntensity: .42, plasmaFlowSpeed: .38, plasmaNoiseScale: .72, plasmaEnergyMix: .35, plasmaSoftness: 1.3, filamentDensity: .35, filamentSpeed: .12, filamentThickness: .014, filamentGlow: .4, filamentPulseStrength: .35, magneticIntensity: .28, fieldStrength: .7, fieldSpeed: .2, fieldDistortion: .35, fieldThickness: .025, fieldOpacity: .32, particleDensity: .45, particleSpeed: .16, particleSize: 3, particleOpacity: .42, particleLife: .9, knowledgeFlow: .4, thoughtPulseStrength: .35, thoughtPulseRadius: .72, thoughtPulseSpeed: .2, thoughtPulseWidth: .04, thoughtPulseGlow: .42, thoughtPulseDecay: .68, communicationStrength: .3, communicationRadius: .88, communicationSpeed: .16, communicationWidth: .035, communicationGlow: .38, communicationDecay: .7, presence: .38, presenceRadius: .78, presenceSoftness: 1, presenceOpacity: .12, presencePulse: .2, distortionIntensity: .55, pulseIntensity: .72, animationSpeed: .55, paused: false },
  energy: { mode: "energy", shaderMode: "composite", bloomIntensity: 1.3, bloomRadius: .88, bloomThreshold: .1, heartIntensity: 1.16, heartPulseSpeed: 1.14, heartRadius: .5, heartNoise: .9, heartGlow: 1.3, plasmaIntensity: 1.38, plasmaFlowSpeed: .82, plasmaNoiseScale: 1.18, plasmaEnergyMix: .62, plasmaSoftness: .85, filamentDensity: 1, filamentSpeed: .32, filamentThickness: .022, filamentGlow: 1, filamentPulseStrength: .9, magneticIntensity: .82, fieldStrength: 1.25, fieldSpeed: .48, fieldDistortion: 1.05, fieldThickness: .045, fieldOpacity: .68, particleDensity: 1.35, particleSpeed: .38, particleSize: 4.8, particleOpacity: .78, particleLife: 1.15, knowledgeFlow: 1, thoughtPulseStrength: 1, thoughtPulseRadius: .94, thoughtPulseSpeed: .42, thoughtPulseWidth: .07, thoughtPulseGlow: 1.1, thoughtPulseDecay: .76, communicationStrength: .95, communicationRadius: 1.3, communicationSpeed: .38, communicationWidth: .06, communicationGlow: 1, communicationDecay: .8, presence: .92, presenceRadius: .98, presenceSoftness: .62, presenceOpacity: .32, presencePulse: .58, distortionIntensity: 1.25, pulseIntensity: 1.22, animationSpeed: 1.2, paused: false },
  experimental: { mode: "experimental", shaderMode: "composite", bloomIntensity: 1.55, bloomRadius: 1, bloomThreshold: .04, heartIntensity: .94, heartPulseSpeed: .85, heartRadius: .52, heartNoise: 1.45, heartGlow: 1.55, plasmaIntensity: 1.65, plasmaFlowSpeed: 1.05, plasmaNoiseScale: 1.5, plasmaEnergyMix: .75, plasmaSoftness: .68, filamentDensity: 1.35, filamentSpeed: .42, filamentThickness: .026, filamentGlow: 1.25, filamentPulseStrength: 1.15, magneticIntensity: 1.1, fieldStrength: 1.5, fieldSpeed: .62, fieldDistortion: 1.45, fieldThickness: .055, fieldOpacity: .82, particleDensity: 1.65, particleSpeed: .52, particleSize: 5.5, particleOpacity: .9, particleLife: 1.25, knowledgeFlow: 1.3, thoughtPulseStrength: 1.3, thoughtPulseRadius: 1.08, thoughtPulseSpeed: .55, thoughtPulseWidth: .085, thoughtPulseGlow: 1.35, thoughtPulseDecay: .82, communicationStrength: 1.2, communicationRadius: 1.48, communicationSpeed: .5, communicationWidth: .075, communicationGlow: 1.3, communicationDecay: .84, presence: 1.15, presenceRadius: 1.08, presenceSoftness: .5, presenceOpacity: .4, presencePulse: .75, distortionIntensity: 1.8, pulseIntensity: 1.4, animationSpeed: .82, paused: false },
};

export const resolveEdiV2LaboratoryProfile = (laboratory?: Partial<EdiV2LaboratoryProfile>): EdiV2LaboratoryProfile => {
  const mode = laboratory?.mode || "prototype";
  return { ...EDI_V2_LABORATORY_PRESETS[mode], ...laboratory, mode };
};
